language: generic


services:
  - docker

install:
  - git clone --depth=1 https://github.com/wirvsvirus-dortmund/backend ../backend
  - git clone --depth=1 https://github.com/wirvsvirus-dortmund/frontend ../frontend
  - cp ci/travis-env .env
  - mkdir -p /tmp/docker-data/backups
  - chmod -R 777 /tmp/docker-data

script:
  - docker-compose up -d --build
  - (timeout 60 docker-compose logs --follow; exit 0)
  - docker-compose down
