---
version: '3'

services:
  nginx-dev:
    image: nginx
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
    network_mode: host

  database:
    image: postgres:11.7
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    networks:
      - supermarkt

  backend:
    build: ../backend
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/backups:/var/backups
    environment:
      - SECRET_KEY
      - DATABASE_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DATABASE}
      - MAIL_SENDER
      - MAIL_SERVER
    expose:
      - 5000
    depends_on:
      - database
    networks:
      - supermarkt

  frontend:
    build: ../frontend
    restart: unless-stopped

    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - backend
    networks:
      - supermarkt

networks:
  supermarkt:
